image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    # - Dart-Code.dart-code@3.10.5-beta.5.gitpod.2:FvtxwrtQZx97jUqxskwTTA==
    - Dart-Code.flutter@3.6.0:bAElIiRvpBSK2AT2+PDj0w==
    - Dart-Code.dart-code@3.10.1:WYFoA7kIknxoDt/Wu6mqZA==
